### ISSUE TITLE
API input validation

### ISSUE THREAD

**Issue by dislocated-su** [RadiationChallengeProjectCAST/RadDataStorage#15]
### Description

Currently the only the token is validated when the API is POSTed to.
All other parameters need to be validated

### Possible solution

* Check for the coordinates to be a positive value.
* Check for the floor to be within range of possible integer values [-1 to 2].
* Check for the CPM to be a non-negative value.

**Comment by tomkettle1** [comment]
Whats the logic behind -1 to 2 for floor?
(I set the autofill in the record page to 1 to 3, so if the users are entering -1 to 2 that needs changing)

**Comment by dislocated-su** [comment]
There is an additional map which is the outside of the school with the playing field.
I'm not sure if we're supporting it, but I gave it a value of -1 in this example.

**Comment by tomkettle1** [comment]
Ah. We need to decide how we're getting people to enter stuff, cos the maps are marked 1-3. Prolly just remember to explain clearly that its 0 - 2 on the form and on the api docs
