### ISSUE TITLE
Add token verification page and api

### ISSUE THREAD

**Issue by TimMcGilly** [RadiationChallengeProjectCAST/RadDataStorage#8]
Page and api to verify token and get team name and team id from token.

**Comment by tomkettle1** [comment]
Would this be for our use or for the teams?

**Comment by TimMcGilly** [comment]
Both. Teams could use it to find their team id for the filtering of results and we can use it to query db and validate tokens. @tomkettle1

**Comment by tomkettle1** [comment]
Ah, makes sense
